hl.config({
	general = {
		border_size = 0,
		gaps_in = 7,
		gaps_out = 12,
		float_gaps = 0,
		gaps_workspaces = 0,
		no_focus_fallback = true,
		allow_tearing = false,
	},
	decoration = {
		rounding = 25,
		rounding_power = 2.0,
		active_opacity = 0.95,
		inactive_opacity = 0.95,
		fullscreen_opacity = 1.0,
		dim_inactive = false,
		dim_strength = 0.5,
		dim_special = 0.7,
		dim_around = 0.7,
		screen_shader = "",
		border_part_of_window = true,
		blur = {
			enabled = true,
			size = 2,
			passes = 3,
			ignore_opacity = true,
			xray = false,
			noise = 0.0117,
			contrast = 0.8916,
			brightness = 0.8172,
			vibrancy = 0.1696,
			vibrancy_darkness = 0.0,
			special = true,
			popups = false,
		},
		shadow = {
			enabled = false,
			range = 9,
			render_power = 1,
			sharp = false,
		},
	},
	misc = {
		disable_splash_rendering = true,
		force_default_wallpaper = 0,
	},
})
